wcs\CoavBundle\Entity\PlaneModel:
    type: entity
    table: plane_model
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        model:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        manufacturer:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        cruisespeed:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: cruiseSpeed
        nbseats:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: nbSeats
        status:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
